### ISSUE TITLE
Set up the Kanban board

### ISSUE THREAD

**Issue by duskotmane** [duskotmane/ruby-capstone#36]
- Here is the link to the project : [Ruby Capstone kanban board](https://github.com/otmaneechchafyky/ruby-capstone/projects/1)

- We are 3 members of the team.
- Members : 

1.  Team member 1 => @otmaneechchafyky.
2. Team member 2 => @luigirazum .
3. Team member 3 => @binodbhusal

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @otmaneechchafyky, @luigirazum and @binodbhusal,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Kindly provide the link to the Kanban board project, instead of your repository.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Gambit142** [comment]
Hi @otmaneechchafyky @luigirazum @binodbhusal 👋, 

Good job so far!

## Highlights
- Created Kanban board from the template given ✔️ 
- All cards are assigned to a team member ✔️ 
- All cards are assigned in a fair way ✔️ 
- All Project requirements are represented by a card ✔️ 

You still need to work on some issues to go to the next project, but you are almost there!

## Required Changes ♻️

- [ ] All cards including those representing the group tasks assigned to @binodbhusal have no task description. Kindly add descriptions to each card 👍

![image](https://github.com/otmaneechchafyky/ruby-capstone/assets/77106962/5fd8a36b-81eb-4a8b-8706-a9957caf8cb8)
 

- [ ] The title of this [card](https://github.com/otmaneechchafyky/ruby-capstone/issues/10) assigned to @binodbhusal should be _**'Add Author table to schema.sql file**_. Kindly correct it for clarity's sake and to avoid confusion when implementing the task. 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

You can also consider the following:

N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by mckent05** [comment]
Hi team, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to start your capstone :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All tasks have been fairly assigned ✔️ ✔️ 
- Your Kanban board has been well set up 👏 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by luigirazum** [comment]
Closing issue once we got Reviewer @mckent05 approval.
Thanks!! 👍
